### PR TITLE
updating ff-server image to 1.1076.0 and timescale db migration image  to 1.945.0

### PR DESCRIPTION
**Pull request by laura135**
updating ff-server image to 1.1076.0 and timescale db migration image to 1.945.0

### CODE REVIEW

**Comment by akshay-khole** [comment]
Added @kapilgarg1996  for review,  @laura135 please add details of testing done and corresponding smp set ups used

**Review by davejohnston — APPROVED** [review]
LGTM

**Comment by laura135** [comment]
@akshay-khole / @kapilgarg1996 - Testing has been done against 1.1076.0 in SaaS. We don't have an smp-like environment at present. 

UI: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/Feature_Flag/projects/FFPipelines/pipelines/Nightwatch_Again/executions/uqE3Z4IoSYmNb5mGH64r1w/pipeline?storeType=INLINE 
System Tests:  https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/Feature_Flag/projects/FFPipelines/pipelines/E2E_Tests/executions?storeType=INLINE

**Comment by akshay-khole** [comment]
@Vbhatia20 @arya-harness  could we share some document/ pipelines for FF team to bring up smp environment and test against ?

**Comment by akshay-khole** [comment]
@laura135  here is how to set up SMP using pipelines https://harness.atlassian.net/wiki/spaces/DEV/pages/21402321705/Build+GKE+Cluster+and+Deploy+Harness
please reach out to @Vbhatia20  or @arya-harness  if you run into any issues

**Comment by laura135** [comment]
Thanks @akshay-khole, I'll try to set up using those today

**Comment by laura135** [comment]
@akshay-khole @arya-harness we've tested in an smp-like environment and all looks well. This is ready to be merged and deployed to smp qa

**Pull request merged**
